name: CI
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: install pnpm
        run: npm i pnpm@latest -g
      - name: Install
        run: pnpm install
      - name: Lint
        run: pnpm run lint-staged
